#+ summary: A query for topics of interest for parts of HiTS
#+ endpoint: https://query.wikidata.org/sparql
#+ tags:
#+   - bibliometrics
#defaultView:Graph

SELECT
  ?lab ?labLabel ?topic ?topicLabel
WHERE {
  ?lab wdt:P361* wd:Q107392274 .  # Get all subunits of HITS
  ?lab wdt:P101 ?topic .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,da,de,es,fr,jp,sv,ru,zh". }
}
ORDER BY ASC(?managerLabel)
