#+ summary: A query for the org. chart of HiTS
#+ endpoint: https://query.wikidata.org/sparql
#+ tags:
#+   - bibliometrics
#defaultView:Graph

SELECT
  ?lab1 ?lab1Label ?lab2 ?lab2Label ?edgeLabel
WHERE {
  ?lab1 wdt:P361* wd:Q107392274 .  # Get all subunits of HITS
  ?lab1 wdt:P361 ?lab2 .  # Get all parents of those subunits
  FILTER (?lab1 != ?lab2) .
  BIND("part of" as ?edgeLabel)
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,da,de,es,fr,jp,sv,ru,zh". }
}
